name: Update GPU Prices
on:
  schedule:
    - cron: '*/15 * * * *' # Обновлять каждые 15 минут
  workflow_dispatch: # Позволяет запустить вручную

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch API
        run: |
          curl "https://vast.ai" > prices.json
      - name: Commit and Push
        run: |
          git config --global user.name "Price Bot"
          git config --global user.email "bot@github.com"
          git add prices.json
          git commit -m "Update prices" || exit 0
          git push
